baseURL: https://sarah-wu-portfolio.netlify.app/
languageCode: en-us
title: Personal Site for Sarah Wu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      GET TO KNOW MY LIFE AND PROFESSIONAL SKILLS
      THROUGH THIS SITE.
    title: Hi, my name is Sarah Wu
    image: 'banner.jpg'
  blog: {}
  contact:
    address: 
      - city: London
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: swu.mam2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (741) 936-1822
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Sarah Wu
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
        #label: Twitter
        #url: https://www.twitter.com
      #- icon: fa-facebook
        #label: Facebook
        #url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/sarah990715/
      - icon: fa-github
        label: GitHub
        url: https://github.com/SarahWu0715
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/sarah-wu-9b0166161
  image: ''
  name: Sarah Wu
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Click to learn about who I am
        title: About Me
        url: blogs/about_me/
      - image: pic02.jpg
        subtitle: Click to see my experiences
        title: My Resume
        url: blogs/SarahWu_resume_revised.pdf/
      - image: pic03.jpg
        subtitle: Click to view my work
        title: Analytical Work 1
        url: blogs/hw0/
      - image: pic03.jpg
        subtitle: Click to view my work
        title: Analytical Work 2
        url: blogs/hw1/
      - image: pic03.jpg
        subtitle: Click to view my work
        title: Analytical Work 3
        url: blogs/hw3/
      - image: pic09.jpg
        subtitle: Click to others' impression on me
        title: Recommendation
        url: blogs/recom/
      - image: pic04.jpg
        subtitle: Click to see my life and interests
        title: Interests
        url: blogs/interest/
      - image: pr.jpg
        subtitle: Click to see my travel log
        title: Life
        url: blogs/travel.html
  two:
    buttonText: Learn More About Me
    enable: yes
    subtitle: "My name is Sarah Wu.\n I am from Beijing China.\n 
    My career interest lies precisely in business analytics, leveraging my data analysis skills and passion for solving business problems."
    title: Brief Introduction
    url: blogs

markup:
  goldmark:
    renderer:
      unsafe: true
